/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mod = IDL.Record({
  'id' : IDL.Text,
  'externalLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'version' : IDL.Text,
  'shortDescription' : IDL.Text,
  'longDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToLibrary' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMod' : IDL.Func([IDL.Text], [IDL.Opt(Mod)], ['query']),
  'getMyLibrary' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromLibrary' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mod = IDL.Record({
    'id' : IDL.Text,
    'externalLinks' : IDL.Opt(IDL.Vec(IDL.Text)),
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'version' : IDL.Text,
    'shortDescription' : IDL.Text,
    'longDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToLibrary' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMods' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMod' : IDL.Func([IDL.Text], [IDL.Opt(Mod)], ['query']),
    'getMyLibrary' : IDL.Func([], [IDL.Vec(Mod)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromLibrary' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };